version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adv_ecommerce
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:




# services:
#   postgres:
#     image: postgres:16
#     container_name: sommaire-db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   nextjs:
#     build:
#       context: .
#       args:
#         NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
#     env_file:
#       - .env
#     depends_on:
#       - postgres
#     ports:
#       - "3000:3000"

# volumes:
#   pgdata:
